[package]
name = "sqlparser"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-segmentation = "1.12.0"
thiserror = "1.0.65"
anyhow = "1.0.91"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
